### PR TITLE
Use jcenter.

### PR DESCRIPTION
**Pull request by plastiv**

### CODE REVIEW

**Comment by JakeWharton** [comment]
Why?

**Comment by xorgate** [comment]
I would think this has to do with google appointing jcenter as the 'official' repo for android

**Comment by JakeWharton** [comment]
All of the artifacts are in Maven Central as well.

**Comment by plastiv** [comment]
org.gradle.api.plugins:gradle-nexus-plugin:0.7.1 is not available at mavenCentral, I guess that is why jcenter is added already https://github.com/JakeWharton/sdk-manager-plugin/blob/master/build.gradle#L3

But latest version com.bmuschko:gradle-nexus-plugin:2.3.1 is present at mavenCentral. so that is not an issue. 

I wanted to keep single repository reference to avoid confusion, but it provoked more discussion then benefit :)

**Pull request closed without merging**
