### PR TITLE
Always self-update the SDK tools before installing build tools

### PR DESCRIPTION
**Pull request by sschuberth**
This is more or less a simplified version of PRs #87, #44, #41, #37, in the sense that it always self-updates the SDK tools before installing the build tools, and does so after resolving the platform tools. The latter is necessary as the SDK tools depend on the platform tools, and resolving the SDK tools first would result in an error like

    Skipping 'Android SDK Tools, revision 24.4.1'; it depends on 'Android SDK Platform-tools, revision 23.1 rc1' which was not installed.

This PR fixes a bunch of issues, mainly issue #43, but also issue #101 and related ones.

### CODE REVIEW

**Comment by pelegb** [comment]
Hi,
I'm using this PR version in a project with multiple subprojects each is android library and one is an app. It seems that the plugin downloasd Android SDK tools 24.4.1 again and again between the different subprojects and between subsequent builds.
It seems that some kind of "already installed" mechanism isn't in place.

Thanks

**Comment by sschuberth** [comment]
Confirmed. I was assuming the `update` command itself to be smart enough to only do the download if there actually *is* something to update. I'll look into it.

**Comment by sschuberth** [comment]
@pelegb Would you mind trying with the updated PR?

**Comment by sschuberth** [comment]
@pelegb Would you mind trying the force-pushed update to this PR?

**Comment by pelegb** [comment]
@sschuberth it doesn't seem to solve the issue. The tools are being updated in each subproject and in each build.

Thanks for the quick response.

**Comment by sschuberth** [comment]
@pelegb Thanks for checking, I believe to have found the issue. Please try again with the new force-pushed version.

**Comment by pelegb** [comment]
@sschuberth I'm receiving "No SDK tools available for update." in subsequent builds. Strange.

**Comment by pelegb** [comment]
I think I found the issue, you need to use listAll instead of listUpdate android command because once installed the tools don't appear in the list anymore

**Comment by sschuberth** [comment]
Why is that an issue? I'd say it works as expected. Once the latest SDK tools have been installed, they naturally are not available for *update* anymore.

**Comment by pelegb** [comment]
Your correct. Thanks

**Comment by sschuberth** [comment]
So can you confirm it's working correctly for you now?

**Comment by pelegb** [comment]
Yes

**Comment by sschuberth** [comment]
Great, thanks for checking!

**Comment by sschuberth** [comment]
Closing this as the Android Gradle plugin 2.2.0 has this feature built-in and this whole project is deprecated now.

**Pull request closed without merging**
